config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :work_times
  resources :veganuary_items
  resources :roles
  devise_for :users
  localized do
    resources :articles
    get 'about_me', to: "static_pages#about_me", as: "about_me"
    get 'contact', to: "static_pages#contact", as: "contact"
    get 'support', to: "static_pages#support", as: "support"
  end
  get 'static_pages/welcome'
  get 'static_pages/test_site'

  namespace :api do
    get 'work_times'
    post 'sync_work_time'
    post 'sync_work_times'
    post 'sync_employees'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#welcome"
end

app/models/article.rb
require 'tree'                 # Load the library


class Article < ApplicationRecord
  has_one_attached :featured_image
  extend FriendlyId
  friendly_id :title, use: :slugged

  before_save :modify_content

  def add_to_tree


  end

  def modify_content

    doc = Nokogiri::HTML.fragment(self.content)
    table_of_content = ""

    root = Tree::TreeNode.new(self.title, 1)

    current_node = root
    parent_node = root
    last_node = root
    current_level = 1


    doc.css("h2, h3, h4, h5, h6").each do |node|
      node['id'] = node.content.parameterize

      level = node.name.delete("^0-9").to_i

      new_node = Tree::TreeNode.new(node.content, level)

      if parent_node.content == level

        if parent_node.parent.blank?
          root << new_node
          parent_node = root
        else
          parent_node.parent << new_node
          parent_node = parent_node.parent
        end

      elsif parent_node.content + 1 == level
        parent_node << new_node
      elsif parent_node.content + 2 == level
        parent_node = last_node
        parent_node << new_node
      elsif parent_node.content > level

        while parent_node.content + 1 != level

          if parent_node.parent.blank?
            parent_node = root
            break
          end

          parent_node = parent_node.parent

        end

        parent_node << new_node
      end

      current_level = level
      last_node = new_node

    end

    root.print_tree

    doc.css("#toc").each do |node|
      node.inner_html = "<hr>" + tree_to_toc(root) + "<hr>"
    end


    self.modified_content = doc.to_html

  end


  def tree_to_toc(tree)

    list = ""

    tree.children.each do |child|

      link = <<~EOF
            <a href="##{child.name.parameterize}">#{child.name}</a>
      EOF

      list = list + "<li>" +  link + "</li>"

      if child.children.present?
        list = list + tree_to_toc(child)
      end
    end


    return "<ul>" + list + "</ul>"
  end


  def modify_content_old

    root = Tree::TreeNode.new('root', self.title)

    #h2 << Tree::TreeNode.new("CHILD2", "Child2 Content")

    #h1.print_tree

    puts "treenode"
    #puts h1


    doc = Nokogiri::HTML.fragment(self.content)
    table_of_content = ""

    current_heading_level = 1
    current_node = root
    last_node = root

    doc.css("h1, h2, h3, h4, h5, h6").each do |node|
      new_node = Tree::TreeNode.new(node.content, node.content)
      node['id'] = node.name.parameterize


      heading_level = node.name.delete("^0-9").to_i
      puts heading_level
      puts current_heading_level
      puts heading_level == (current_heading_level + 1)


      if heading_level == (current_heading_level + 1)
        current_node << new_node

      elsif heading_level > (current_heading_level + 1)
        current_node = last_node

        current_node << new_node

        current_heading_level = heading_level - 1

      else

        current_node = root
        current_node << new_node
        current_heading_level = heading_level - 1
      end

      last_node = new_node



      times_of_space = node.name.delete("^0-9").to_i
      puts "node"
      #puts node.attributes
      #puts node.methods
      #puts node.name
      #puts node.children.count
      #puts node.children[0].content
      node['id'] = node.content.parameterize

      times_of_space_string = ""
      times_of_space.times do |time|
          times_of_space_string += "&nbsp;&nbsp;&nbsp;&nbsp;"
      end
link = <<~EOF
      <a href="##{node.content.parameterize}">#{node.content}</a>
      <br>
EOF

      table_of_content = table_of_content + times_of_space_string + link
    end

    #https://developer.squareup.com/blog/challenge-table-of-contents-generator/
    self.modified_content = table_of_content + "<hr>" + doc.to_html

    root.print_tree
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all

    set_meta_tags title: "Meine Artikel",
              description: "Artikel von Sandro Räss"
  end

  # GET /articles/1 or /articles/1.json
  def show

    featured_image_url = @article.featured_image.attached? ? rails_blob_url(@article.featured_image) : ""

    set_meta_tags title: @article.title,
              description: @article.seo_description,
              og: {
                title: :title,
                description: :description,
                type:     'article',
                url:      article_url(@article),
                image:    featured_image_url,
            },
            article: {
              published_time:    @article.created_at.iso8601,
              modified_time:     @article.updated_at.iso8601,
            },
            twitter: {
              title: :title,
              description: :description,
              #card:  "summary_large_image",
              card: {
                _: "summary_large_image",
                image: featured_image_url
              },
              image: featured_image_url,
              url: article_url(@article)
            }



  end

  # GET /articles/new
  def new
    @article = Article.new
    authorize @article
  end

  # GET /articles/1/edit
  def edit
    authorize @article

  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    authorize @article

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    authorize @article

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    authorize @article

    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :sub_title, :content, :seo_description, :featured_image, :created_at)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<article id="<%= dom_id article %>" class="article">
  <% if article.featured_image.representable? %>
    <div class="container">
      <div class="row">
        <div class="col-12 col-md-6 offset-md-3"
      </div>
      <%= image_tag article.featured_image, class: "img-fluid"%>
    </div>
  </div>
  <% end %>
  <div class="container-fluid py-2 mt-3 ">
    <div class="container">
      <header class="my-3">
        <h1 class="text-center"><%= article.title %></h1>
        <p class="lead text-center">
          <%= article.sub_title %>
        </p>
      </header>
    </div>
  </div>
  <div class="container">
    <p>
    <small class="text-muted">
      Sandro Räss
       -
      <%= l(article.created_at, format: :short) %>
    </small>
    </p>
    <hr>
    <div class="row">
      <div class="col-12 col-lg-12">

        <div class="content">
          <%= raw article.modified_content %>
        </div>
      </div>

      <!--
      <div class="col-12 col-lg-3">
        <%#= render "static_pages/about_me_card" %>
      </div>
      -->
    </div>
  </div>


</article>

app/views/articles/_article_grid.html.erb
<div class="row">

  <div class="col-12 col-md-8">
    <%= render @article %>
  </div>

  <div class="col-12 col-md-4">
    card
  </div>

</div>

app/views/articles/_articles.html.erb
<div id="articles" class="my-5">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
    <% articles.order(created_at: :desc).each do |article| %>
    <div class="col">
      <% cache article do %>
        <%= render "articles/card", article: article %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<% if policy(Article).new? %>
  <%= link_to "New article", new_article_path %>
<% end %>

app/views/articles/_card.html.erb
<div class="card h-100 border-0 shadow-lg article_card">
  <% if article.featured_image.representable? %>
      <%= image_tag article.featured_image, class: "card-img-top", width: 300, height: 250, style: "object-fit: cover"%>
  <% end %>
  <div class="card-body">
    <small class="text-muted">
      <%= l(article.created_at, format: :short) %>
    </small>
    <h2 class="card-title"><%= article.title %></h2>
    <hr>
    <p class="card-text"><%= article.seo_description %></p>

  </div>
  <div class="card-footer bg-white border-top-0">
    <div class="d-grid gap-2">
      <%= link_to t("read"), article, class: "btn btn-primary mb-2" %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.file_field :featured_image %>

    <%= f.input :title %>
    <%= f.input :sub_title %>
    <%= f.input :created_at %>

    <%#= f.input :content %>
  <div data-controller="tinymce">
    <%= f.text_area :content, class: "tinymce-textarea", data: {"tinymce-target": "textarea"} %>
  </div>
    <%= f.input :seo_description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<%= render "layouts/navigation" %>

<p style="color: green"><%= notice %></p>

<div class="container">
  <h1 class="text-center">Meine Artikel</h1>

  <%= render "articles/articles", articles: Article.all %>
</div>

<%= render "layouts/footer" %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<%= render "layouts/navigation" %>

<% content_for :canonical do %>
  <link rel="canonical" href="<%= article_url(@article) %>" />
<% end %>

<% content_for :json_ld do %>

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "<%= article_url(@article) %>"
  },
  "headline": "<%= @article.title %>",
  "description": "<%= @article.seo_description %>",
  "articleBody": "<%= strip_tags(@article.content) %>",
  "image": "<%= rails_blob_url(@article.featured_image) if @article.featured_image.attached? %>",
  "author": {
    "@type": "Person",
    "name": "Sandro Räss",
    "url": "<%= about_me_url %>"
  },
  "datePublished": "<%= @article.created_at.strftime("%F") %>",
  "dateModified": "<%= @article.updated_at.strftime("%F") %>"
}
</script>

<% end %>

<p style="color: green"><%= notice %></p>

<main>
  <% cache @article do %>
    <%= render @article %>
  <% end %>
</main>


<% if policy(@article).edit? %>
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>
<% end %>

<%#= render "static_pages/support_section" %>
<%#= render "static_pages/donation1_section" %>


<%= render "static_pages/about_me_section" %>


<%= render "layouts/footer" %>