config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :work_times
  resources :veganuary_items
  resources :roles
  devise_for :users
  localized do
    resources :articles
    get 'about_me', to: "static_pages#about_me", as: "about_me"
    get 'contact', to: "static_pages#contact", as: "contact"
    get 'support', to: "static_pages#support", as: "support"
  end
  get 'static_pages/welcome'
  get 'static_pages/test_site'

  namespace :api do
    get 'work_times'
    post 'sync_work_time'
    post 'sync_work_times'
    post 'sync_employees'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#welcome"
end

app/models/work_time.rb
class WorkTime < ApplicationRecord

  def self.createOrUpdate(work_time_params)
    #check if work time exists

    #work_time_params["updated_at"] = DateTime.parse(work_time_params["updated_at"])
    #work_time_params["updated_at"] = Time.at(work_time_params["updated_at"]).to_datetime
    work_times_with_global_work_time_ids = WorkTime.where(globalWorkTimeId: work_time_params["globalWorkTimeId"])
    work_time = nil

    if work_times_with_global_work_time_ids.empty?
      work_time = WorkTime.create(work_time_params)
    elsif work_times_with_global_work_time_ids.count == 1
      work_time = work_times_with_global_work_time_ids.first

      if work_time.updated_at < work_time_params["updated_at"].to_datetime
        work_time.update(work_time_params)
      end

    else
      work_time = work_times_with_global_work_time_ids.first

      work_time_ids = work_times_with_global_work_time_ids.pluck(:id)

      work_time_ids_to_be_deleted = work_time_ids - [work_time.id]

      WorkTime.where(id: work_time_ids_to_be_deleted).delete_all

      if work_time.updated_at < work_time_params["updated_at"].to_datetime
        work_time.update(work_time_params)
      end

    end

    return work_time
  end

end

app/controllers/work_times_controller.rb
class WorkTimesController < ApplicationController
  before_action :set_work_time, only: %i[ show edit update destroy ]

  # GET /work_times or /work_times.json
  def index
    @work_times = WorkTime.all.order(created_at: :desc)
  end

  # GET /work_times/1 or /work_times/1.json
  def show
  end

  # GET /work_times/new
  def new
    @work_time = WorkTime.new
  end

  # GET /work_times/1/edit
  def edit
  end

  # POST /work_times or /work_times.json
  def create
    @work_time = WorkTime.new(work_time_params)

    respond_to do |format|
      if @work_time.save
        format.html { redirect_to work_time_url(@work_time), notice: "Work time was successfully created." }
        format.json { render :show, status: :created, location: @work_time }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_times/1 or /work_times/1.json
  def update
    respond_to do |format|
      if @work_time.update(work_time_params)
        format.html { redirect_to work_time_url(@work_time), notice: "Work time was successfully updated." }
        format.json { render :show, status: :ok, location: @work_time }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_times/1 or /work_times/1.json
  def destroy
    @work_time.destroy

    respond_to do |format|
      format.html { redirect_to work_times_url, notice: "Work time was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_time
      @work_time = WorkTime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_time_params
      params.require(:work_time).permit(:minutes, :content, :deleted, :globalWorkTimeId)
    end
end

app/helpers/work_times_helper.rb
module WorkTimesHelper
end

app/views/work_times/_form.html.erb
<%= simple_form_for(@work_time) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :minutes %>
    <%= f.input :content %>
    <%= f.input :deleted %>
    <%= f.input :globalWorkTimeId %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/work_times/_work_time.html.erb
<div id="<%= dom_id work_time %>">
  <p>
    <strong>Minutes:</strong>
    <%= work_time.minutes %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= work_time.content %>
  </p>

  <p>
    <strong>Deleted:</strong>
    <%= work_time.deleted %>
  </p>

  <p>
    <strong>Globalworktimeid:</strong>
    <%= work_time.globalWorkTimeId %>
  </p>

  <p>
    <strong>employee id:</strong>
    <%= work_time.employee_global_employee_id %>
  </p>

  <p>
    <%= work_time.created_at %>
  </p>
  <p>
    <%= work_time.updated_at %>
  </p>

</div>

app/views/work_times/edit.html.erb
<h1>Editing work time</h1>

<%= render "form", work_time: @work_time %>

<br>

<div>
  <%= link_to "Show this work time", @work_time %> |
  <%= link_to "Back to work times", work_times_path %>
</div>

app/views/work_times/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Work times</h1>

<div id="work_times">
  <% @work_times.each do |work_time| %>
    <%= render work_time %>
    <p>
      <%= link_to "Show this work time", work_time %>
    </p>
  <% end %>
</div>

<%= link_to "New work time", new_work_time_path %>

app/views/work_times/new.html.erb
<h1>New work time</h1>

<%= render "form", work_time: @work_time %>

<br>

<div>
  <%= link_to "Back to work times", work_times_path %>
</div>

app/views/work_times/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @work_time %>

<div>
  <%= link_to "Edit this work time", edit_work_time_path(@work_time) %> |
  <%= link_to "Back to work times", work_times_path %>

  <%= button_to "Destroy this work time", @work_time, method: :delete %>
</div>