config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :work_times
  resources :veganuary_items
  resources :roles
  devise_for :users
  localized do
    resources :articles
    get 'about_me', to: "static_pages#about_me", as: "about_me"
    get 'contact', to: "static_pages#contact", as: "contact"
    get 'support', to: "static_pages#support", as: "support"
  end
  get 'static_pages/welcome'
  get 'static_pages/test_site'

  namespace :api do
    get 'work_times'
    post 'sync_work_time'
    post 'sync_work_times'
    post 'sync_employees'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#welcome"
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-a-color">
  <div class="container">
    <div class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to 'Edit account', edit_user_registration_path, class: "nav-link px-2 text-muted" %></li>
          <li class="nav-item"><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: "nav-link px-2 text-muted"  %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Sign in', new_user_session_path, class: "nav-link px-2 text-muted"  %></li>
          <li class="nav-item"><%= link_to 'Sign up', new_user_registration_path, class: "nav-link px-2 text-muted"  %></li>
        <% end %>
      </ul>
      <p class="text-center text-muted"><%= t("application_name") %></p>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm bg-c-color navbar-dark">
  <div class="container-fluid">
    <%= link_to t("application_name"), root_path, class: "navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to t("about_me"), about_me_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to Article.model_name.human(count: 2), articles_path, class: "nav-link text-white" %>
        </li>
        <% if false %>
          <li class="nav-item">
            <%= link_to t("support"), support_path, class: "nav-link text-white" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to t("contact"), contact_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Web-Applikationen", "https://web-applikationen.sandro-raess.ch/" , class: "nav-link text-white"%>
        </li>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de" class="h-100">
  <head>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-D3XSEKK6YR"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-D3XSEKK6YR');
    </script>

    <%= display_meta_tags site: 'Sandro Räss', reverse: true %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :canonical %>
    <%= yield :json_ld %>

    <%= favicon_link_tag asset_path('favicon.ico') %>

  </head>

  <body class="d-flex flex-column h-100 bg-b-color">
    <%= yield %>
  </body>
</html>

app/views/layouts/application_vegan.html.erb
<!DOCTYPE html>
<html lang="de" class="h-100">
  <head>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-D3XSEKK6YR"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-D3XSEKK6YR');
    </script>

    <%= display_meta_tags site: 'Sandro Räss', reverse: true %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :canonical %>
    <%= yield :json_ld %>

    <%= favicon_link_tag asset_path('favicon.ico') %>

  </head>

  <body class="d-flex flex-column h-100">
    <%= yield %>
  </body>
</html>